ka-lite/kalite/facility/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url

from . import api_urls


urlpatterns = patterns(__package__ + '.views',
    url(r'^teacher/$', 'add_facility_teacher', {},'add_facility_teacher'),
    url(r'^student/$', 'add_facility_student', {}, 'add_facility_student'),
    url(r'^signup/$', 'facility_user_signup', {}, 'facility_user_signup'),
    url(r'^user/(?P<facility_user_id>\w+)/edit/$', 'edit_facility_user', {}, 'edit_facility_user'),

    url(r'^zone/(?P<zone_id>\w+)/facility/new/$', 'facility_edit', {"id": "new"}, 'add_facility'),
    url(r'^facility/(?P<id>\w+)/edit/$', 'facility_edit', {}, 'facility_edit'),

    url(r'^group/$', 'group_edit', {'group_id': 'new'}, 'add_group'),
    url(r'^group/(?P<group_id>\w+)/edit/$', 'group_edit', {'facility': None}, 'group_edit'),

   
)

if not settings.CENTRAL_SERVER:
    urlpatterns += patterns(__package__ + '.views',
        url(r'^login/$', 'login', {}, 'login'),
        url(r'^logout/$', 'logout', {}, 'logout'),
    )

urlpatterns += patterns(__package__ + '.api_views',
    url(r'^api/', include(api_urls)),
)

ka-lite/kalite/playlist/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(__package__ + '.views',
                       url(r'^assign/$', 'assign_playlists', {}, 'assign_playlists'),
                       url(r'^view/(?P<playlist_id>\w+)/$', 'view_playlist', {}, 'view_playlist'),
)

ka-lite/kalite/store/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url

from . import api_urls


urlpatterns = patterns(__package__ + '.views',
    url(r'^$', 'store', {},'store'),
)

ka-lite/kalite/updates/urls.py
from django.conf.urls import patterns, url, include


urlpatterns = patterns(__package__ + '.views',
    url(r'^videos/$', 'update_videos', {}, 'update_videos'),
    url(r'^languages/$', 'update_languages', {}, 'update_languages'),
    url(r'^software/$', 'update_software', {}, 'update_software')


)

ka-lite/kalite/facility/models.py
"""
"""
from __future__ import absolute_import

import datetime
import uuid
import zlib
from annoying.functions import get_object_or_None
from pbkdf2 import crypt

from django.conf import settings; logging = settings.LOG
from django.contrib.auth.models import check_password
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.db import models, transaction
from django.db.models import Q
from django.utils.text import compress_string
from django.utils.translation import ugettext_lazy as _

from fle_utils.config.models import Settings
from fle_utils.django_utils import verify_raw_password
from securesync.models import DeviceZone
from securesync.engine.models import DeferredCountSyncedModel


class Facility(DeferredCountSyncedModel):
    name = models.CharField(verbose_name=_("Name"), help_text=_("(This is the name that students/teachers will see when choosing their facility; it can be in the local language.)"), max_length=100)
    description = models.TextField(blank=True, verbose_name=_("Description"))
    address = models.CharField(verbose_name=_("Address"), help_text=_("(Please provide as detailed an address as possible.)"), max_length=400, blank=True)
    address_normalized = models.CharField(max_length=400, blank=True)
    latitude = models.FloatField(blank=True, verbose_name=_("Latitude"), null=True)
    longitude = models.FloatField(blank=True, verbose_name=_("Longitude"), null=True)
    zoom = models.FloatField(blank=True, verbose_name=_("Zoom"), null=True)
    contact_name = models.CharField(verbose_name=_("Contact Name"), help_text=_("(Who should we contact with any questions about this facility?)"), max_length=60, blank=True)
    contact_phone = models.CharField(max_length=60, verbose_name=_("Contact Phone"), blank=True)
    contact_email = models.EmailField(max_length=60, verbose_name=_("Contact Email"), blank=True)
    user_count = models.IntegerField(verbose_name=_("User Count"), help_text=_("(How many potential users do you estimate there are at this facility?)"), blank=True, null=True)

    class Meta:
        verbose_name_plural = _("Facilities")
        app_label = "securesync"  # for back-compat reasons

    def __unicode__(self):
        if not self.id:
            return self.name
        return u"%s (#%s)" % (self.name, int(self.id[:3], 16))

    def is_default(self):
        return self.id == Settings.get("default_facility")

    @classmethod
    def from_zone(cls, zone):
        """Our best approximation of how to map facilities to zones"""

        facilities = set(Facility.objects.filter(zone_fallback=zone))

        for device_zone in DeviceZone.objects.filter(zone=zone):
            device = device_zone.device
            facilities = facilities.union(set(Facility.objects.filter(signed_by=device)))

        return facilities

    @classmethod
    def initialize_default_facility(cls, facility_name=None):
        facility_name = facility_name or getattr(settings, "INSTALL_FACILITY_NAME", None) or unicode(_("Default Facility"))

        # Finally, install a facility--would help users get off the ground
        facilities = Facility.objects.filter(name=facility_name)
        if facilities.count() == 0:
            # Create a facility, set it as the default.
            facility = Facility(name=facility_name)
            facility.save()
            Settings.set("default_facility", facility.id)

        elif Settings.get("default_facility") not in [fac.id for fac in facilities.all()]:
            # Use an existing facility as the default, if one of them isn't the default already.
            Settings.set("default_facility", facilities[0].id)


class FacilityGroup(DeferredCountSyncedModel):
    facility = models.ForeignKey(Facility, verbose_name=_("Facility"))
    name = models.CharField(max_length=30, verbose_name=_("Name"))
    description = models.TextField(blank=True, verbose_name=_("Description")); description.minversion = "0.13.0" # TODO-BLOCKER(jamalex): change this to the specific version it is at the time it ships

    def __init__(self, *args, **kwargs):
        super(FacilityGroup, self).__init__(*args, **kwargs)
        self._unhashable_fields.append("description") # since it's being stripped out by minversion, we can't include it in the signature

    class Meta:
        app_label = "securesync"  # for back-compat reasons

    def __unicode__(self):
        return self.name

    @transaction.commit_on_success
    def soft_delete(self):
        """
        As FacilityGroup acts as a soft wrapper around FacilityUser entities, upon soft deletion
        we 'evict' the FacilityUsers rather than the default behaviour of soft deleting all the
        entities that ForeignKey onto the object. As such, we completely overwrite the super
        soft_delete method.
        """

        self.deleted = True  # mark self as deleted

        # This is not very robust, as it relies on explicitly calling the reverse relations to the model
        # and then clearing them. If anything else Foreign Keys onto groups here, it will have to be set here.
        # Note that we cannot simply call .clear() on the reverse relation, as then the user models are not signed.
        for user in self.facilityuser_set.all():
            user.group = None
            user.save()

        self.save()

    def get_zone(self, *args, **kwargs):
        zone = super(FacilityGroup, self).get_zone(*args, **kwargs)

        # if we don't have a zone based on signed_by or zone_fallback, use zone of associated Facility
        if not zone:
            zone = self.facility.get_zone()

        return zone

    @property
    def title(self):
        if self.description:
            return "%s - %s" % (self.name, self.description,)
        return self.name


class FacilityUser(DeferredCountSyncedModel):
    # Translators: This is a label in a form.
    facility = models.ForeignKey(Facility, verbose_name=_("Facility"))
    # Translators: This is a label in a form.
    group = models.ForeignKey(FacilityGroup, verbose_name=_("(Group/class)"), blank=True, null=True, help_text=_("(optional)"))
    # Translators: This is a label in a form.
    username = models.CharField(max_length=30, verbose_name=_("Username"))
    # Translators: This is a label in a form.
    first_name = models.CharField(max_length=30, verbose_name=_("First Name"), blank=True)
    # Translators: This is a label in a form.
    last_name = models.CharField(max_length=60, verbose_name=_("Last Name"), blank=True)
    # Translators: This is a label in a form.
    is_teacher = models.BooleanField(default=False, help_text=_("(whether this user should have teacher permissions)"))
    notes = models.TextField(blank=True)
    password = models.CharField(max_length=128)
    default_language = models.CharField(max_length=8, blank=True, null=True); default_language.minversion="0.11.1"

    class Meta:
        app_label = "securesync"  # for back-compat reasons

    def __unicode__(self):
        return u"%s (Facility: %s)" % (self.get_name(), self.facility)

    def save(self, *args, **kwargs):
        """
        Validate password format before saving
        """
        # Now, validate password.
        if self.password.split("$", 1)[0] == "sha1":
            # Django's built-in password checker for SHA1-hashed passwords
            pass
        elif len(self.password.split("$", 2)) == 3 and self.password.split("$", 2)[1] == "p5k2":
            # PBKDF2 password checking
            # Could fail if password doesn't split into parts nicely
            pass
        elif self.password is not None:
            raise ValidationError(_("Unknown password format."))
        else:
            raise ValidationError(_("Call set_password before saving the user."))

        # Now, validate group:
        if self.group and self.facility and self.group.facility != self.facility:
            raise ValidationError(_("Facility group must be in the same facility as the user."))

        super(FacilityUser, self).save(*args, **kwargs)

        # in case the password was changed on another server, and then synced into here, clear cached password
        CachedPassword.invalidate_cached_password(user=self)

    def check_password(self, raw_password):
        cached_password = CachedPassword.get_cached_password(self)
        cur_password = cached_password or self.password

        # Check the password
        if cur_password.split("$", 1)[0] == "sha1":
            # use Django's built-in password checker for SHA1-hashed passwords
            okie_dokie = check_password(raw_password, cur_password)
        elif cur_password.split("$", 2)[1] == "p5k2":
            # use PBKDF2 password checking
            okie_dokie = cur_password == crypt(raw_password, cur_password)
        else:
            raise ValidationError(_("Unknown password format."))

        # Update on cached password-relevant stuff
        if okie_dokie and not cached_password and self.id:  # only can create if the user's been saved
            CachedPassword.set_cached_password(self, raw_password=raw_password)

        return okie_dokie

    def set_password(self, raw_password=None, hashed_password=None, cached_password=None):
        """Set a password with the raw password string, or the pre-hashed password.
        If using the raw string, """
        assert hashed_password is None or settings.DEBUG, "Only use hashed_password in debug mode."
        assert raw_password is not None or hashed_password is not None, "Must be passing in raw or hashed password"
        assert not (raw_password is not None and hashed_password is not None), "Must be specifying only one--not both."

        if raw_password:
            verify_raw_password(raw_password)

        if hashed_password:
            self.password = hashed_password

            # Can't save a cached password from a hash, so just make sure there is none.
            # Note: Need to do this, even if they're not enabled--we don't want to risk

ka-lite/kalite/facility/templates/facility/facility.html
{% extends "distributed/base_manage.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}
    {% if form.instance.id %}
        {% trans "Edit" %}
    {% else %}
        {% trans "Add" %}
    {% endif %}
    {% trans "Facility" %}
{% endblock title %}
{% block facility_active %}facility-active active-tab active-nav{% endblock facility_active %}
{% block update_active %}active{% endblock update_active %}
{% block users_active %}active{% endblock %}

{% block headcss %}
    <style>
        #map_canvas {
            display: none;
            margin-bottom: 30px;
            width: 100%;
            height: 400px
        }
        #search-panel {
            width: 550px;
            z-index: 5;
            background-color: #fff;
            padding: 5px;
            margin-bottom: 10px;
            border: 1px solid #999;
        }
        #search-panel input {
            font-size: 12px;
            width: 100%;
        }
        #target {
            width: 545px;
        }
        span.helptext {
            margin-top: 5px;
        }
        #id_name {
            width: 300px;
        }
        #id_address {
            width: 500px;
        }
        #id_latitude, #id_longitude {
            width: 150px;
        }
        #id_direc_map {
            display: none;
            padding-bottom: 10px;
            font-size: 14px;
        }
        #id_direc_no_map {
            padding-bottom: 10px;
            font-size: 14px;
        }
        @media only screen and (max-width: 596px) {
            #search-panel { width: 100%; }
        }
        @media only screen and (max-width: 532px) {
            #search-panel { border: none; padding: 0; }
            #search-panel input { font-size: 8.5px; }
            #id_address { width: 100%; }
        }
    </style>
{% endblock headcss %}

{% block headjs %}{{ block.super }}
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCUVMGp6Uks8OCczFfrWo20zHnmENyW5O0&v=3.9&sensor=false&libraries=places"></script>
    <script type="text/javascript">
        $(function() {
            $('#id_address_normalized').parent().hide();
            $('#id_zoom').parent().hide();
            $('#id_latitude').parent().hide();
            $('#id_longitude').parent().hide();
        });

        function displayFormLatLng(map, marker) {
            var longitude = $("#id_longitude").val();
            var latitude = $("#id_latitude").val();
            if (longitude && latitude) {
                var latLng = new google.maps.LatLng(latitude, longitude);
                map.setCenter(latLng);
                marker.setPosition(latLng);
                marker.setVisible(true);
            }
        }


        function saveLatLng(lat, lon) {
            $("#id_latitude").val(lat);
            $("#id_longitude").val(lon);
        }

        function getAddress(ad) {
            $("#id_address_normalized").val(ad);
        }

        function saveZoom(zm) {
            $("#id_zoom").val(zm);
        }

        function initialize()
        {
            var map = new google.maps.Map(document.getElementById('map_canvas'), {
                mapTypeId: google.maps.MapTypeId.SATELLITE,
                scrollwheel: false,
                maxZoom: 20,
                minZoom: 3,
            });
            var defaultBounds = new google.maps.LatLngBounds(
                new google.maps.LatLng(-33.8902, 151.1759),
                new google.maps.LatLng(-33.8474, 151.2631));
            map.fitBounds(defaultBounds);

            var input = document.getElementById('target');
            var searchBox = new google.maps.places.Autocomplete(input);

            var myLatLng = new google.maps.LatLng(-33.8902, 151.1759);

            var marker = new google.maps.Marker({
                position: myLatLng,
                map: map,
                draggable: true,
                visible: false,
                clickable: true,
            });

            saveZoom(map.getZoom());

            google.maps.event.addListener(map, 'click', function(ev) {
                    marker.setVisible(true);
                    marker.setPosition(ev.latLng);
                    saveLatLng(ev.latLng.lat(), ev.latLng.lng());
            });


            google.maps.event.addListener(searchBox, 'place_changed', function() {
                var place = searchBox.getPlace();
                var bounds = new google.maps.LatLngBounds();

                marker.setVisible(true);
                marker.setPosition(place.geometry.location);
                bounds.extend(place.geometry.location);
                saveLatLng(place.geometry.location.lat(), place.geometry.location.lng());
                getAddress(place.formatted_address);
                // if a place has a geometry, display it on the map
                if (place.geometry.viewport) {
                    map.fitBounds(place.geometry.viewport);
                    marker.setPosition(place.geometry.viewport);
                }
                else {
                    map.setCenter(place.geometry.location);
                    map.setZoom(13);
                }
            });

            $('#map_canvas').show();
            $('#id_direc_no_map').hide();
            $('#id_direc_map').show();
            google.maps.event.addListenerOnce(map, 'idle', function() {
                displayFormLatLng(map, marker);
            });

            google.maps.event.addListener(map, 'zoom_changed', function(){
                saveZoom(map.getZoom());
            });
        }

        if (window.google) {
            google.maps.event.addDomListener(window, 'load', initialize);
        }
    </script>
{% endblock headjs %}

{% block content %}

    {{ block.super }}
 
    <h3 class="no-margin-top">{% if form.instance.id %}{% trans "Edit a facility" %}{% else %}{% trans "Add a new Facility" %}{% endif %}</h3>
    <div id="id_direc_no_map">{% trans "Please enter the following information about your facility. Please enter a detailed address, because knowing where you are in the world allows us to better plan for future deployments and partnerships." %}</div>
    <div id="id_direc_map">
        {% trans "Please use this search box to locate your facility (and/or click on the map to select a spot), and then enter the additional information in the form below." %}<br/>
        {% trans "(Knowing, as closely as possible, where you are in the world allows us to better plan for future deployments and partnerships)" %}
    </div>
    <div id="search-panel">
        {% trans "Search for your facility's address or name to find its location on the map (enter to search)" as placeholder %}
        <input id="target" type="text" placeholder="{{placeholder}}">
    </div>
    <div id="map_canvas"></div>
    <form id="facility_form" method="post" class="basic-form">
        {% csrf_token %}
        {% for field in form %}
          <p>
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
            <span class="helptext">{{ field.help_text }}</span>
          </p>
        {% endfor %}
        {% trans "Save facility" as value %}
        <input type="submit" value="{{ value }}" class="submit btn btn-default btn-sm"/>
    </form>
{% endblock content %}

ka-lite/kalite/facility/templates/facility/facility_group.html
{% extends "facility/facility.html" %}
{% load i18n %}

{% block headcss %}{{ block.super }}
    <style>
        #id_facility {
            display: none;
        }
    </style>
{% endblock headcss %}

{% block headjs %}{{ block.super }}
    <script>
        $(function () {
            $('#facility_group').change(function(){
                window.location.href = $("#facility_group option:selected").val();
            });

        {# Show facility info #}
        {% if not singlefacility %}
            // Show the dropdown
            $("#id_facility").show();
        {% else %}
            // Show that there's only one facility, and it's being selected.
            $(sprintf("<span>%s</span>", $("#id_facility option:selected").text())).insertAfter($("#id_facility"));
        {% endif %}
        });
    </script>
{% endblock headjs %}

{% block content %}
{% block manage_nav %}{{block.super}}{% endblock manage_nav %}
    <h3 class="no-margin-top">{{ title }}</h3>

    <form method="post" class="basic-form">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" class="submit btn btn-default btn-sm" value="{% if group_id == 'new' %}{% trans 'Create group' %}{% else %}{% trans 'Update group' %}{% endif %}" />
    </form>
{% endblock content %}

ka-lite/kalite/facility/templates/facility/facility_selection.html
{% extends "facility/facility.html" %}
{% load i18n %}
{% load my_filters %}

{% block title %}{% trans "Select facility" %} {{ block.super }}{% endblock title %}

{% block headcss %}{{ block.super }}
    <style>
/*        .default-setter {
            font-size: 14px;
        }*/
        section#facility_list {
            margin-bottom: 20px;
        }
        .facility_title a {
            font-size: 1.25em;
        }
        #id_default_language {
            margin-top: 10px;
            margin-bottom: 10px;
        }
    </style>
{% endblock headcss %}


{% block content %}
{% block manage_nav %}{{block.super}}{% endblock manage_nav %}
    {{ path_template }}
    <div id="facility_list_container">
        <section id="facility_list">
            <h2>{% trans "Please select a facility" %}</h2>
            <p>{% trans "A facility is a physical location where students learn." %}</p>
        </section>
        <div>
            <ul>
                {% if facilities %}
                    {% for facility in facilities %}
                    <li class="facility_title">
                            <a href="{{ selection_paths|get_item:facility.id }}">{{ facility }}</a>
                            {% if request.is_admin and facilities.count > 1 %}
                                {% if facility.is_default %}
                                <span class=default-setter>{% trans "(this is the default)" %}</span>
                                {% else %}
                                <a class=default-setter href="{{ selection_paths|get_item:facility.id  }}?set_default=True">
                                {% trans "(set as the default facility)" %}
                                </a>
                                {% endif %}
                            {% endif %}
                    </li>
                    {% endfor %}
                {% else %}
                    {% if request.is_admin %}
                        <li>{% trans "You currently have no facilities. Would you like to create a facility?" %}</li>
                    {% else %}
                        <li>{% trans "There are currently no facilities available, please ask an administrator or teacher to set one up." %}</li>
                    {% endif %}
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock content %}

ka-lite/kalite/facility/templates/facility/facility_user.html
{% extends "distributed/base_manage.html" %}
{% load i18n %}

{% block title %}{% trans title %}{% endblock title %}

{% block facility_active %}facility-active active-tab active-nav{% endblock facility_active %}
{% block users_active %}active{% endblock %}
{% block signup_active %}active{% endblock signup_active %}

{% block headcss %}{{ block.super }}
    <style>
        #id_group {
            margin-bottom: 5px;
        }
    </style>
{% endblock headcss %}

{% block headjs %}{{ block.super }}
    <script>
        var DEFAULT_LANGUAGE = "{{ default_language }}";
        $(function() {
            // Guarantee that SOME language code is either SELECTED by the back-end,
            // or selected to the default value in the front-end.
            if ($('#id_default_language option[selected]').length == 0) {
                $("#id_default_language").val(DEFAULT_LANGUAGE);
            }

        {# Allow admins to add a new group #}
        {% if request.is_admin %}
            {% trans "Add a new group" as add_new_group %}
            $('#id_group').parent().find(".helptext").html('(<a href="{% url 'add_group' %}?facility={{facility.id}}&next={{ request.get_full_path|urlencode }}">{{add_new_group}}</a>)');
        {% elif form.fields.group.choices.queryset.count == 0 %}
            $('#id_group').parent().hide();
        {% endif %}

        {# Do not allow teacher accounts to be in a group. #}
        {% if request.is_admin and teacher %}
            $("#id_group").attr('disabled',true);
            $("#id_group").parent().hide();
        {% endif %}

        {# Do not allow students to edit their own group #}
        {% if not request.is_admin %}
            $("#id_group").hide();
            $('#id_group').siblings('.helptext').hide()
            var group_name = $("#id_group option:selected").text()
            if (group_name === "---------") {
                group_name = "{% trans 'None' %}"
            } 
            $(sprintf("<span>%s</span>", group_name)).insertAfter($("#id_group"));
        {% endif %}        

        {# Show facility info #}
        {% if request.session.facility_count > 1 %}
            // Show the dropdown
            $("#id_facility").show();
        {% else %}
            // Show that there's only one facility, and it's being selected.
            $(sprintf("<span>%s</span>", $("#id_facility option:selected").text())).insertAfter($("#id_facility"));
        {% endif %}
        });
    </script>
{% endblock headjs %}

{% block content %}
    {{ block.super }}

    <div class="container">
        <h3 class="no-margin-top">{{ title }}</h3>
        <form method="post" class="basic-form">
            {% csrf_token %}

            {{ form.as_p }}

            <input type="submit" class="submit btn btn-success btn-md" value="{% if new_user %}{% trans 'Create user' %}{% else %}{% trans 'Update user' %}{% endif %}" />
        </form>

    </div>

{% endblock content %}

ka-lite/kalite/facility/templates/facility/login.html
{% extends base_template %}
{% load i18n %}

{% block login_active %}active{% endblock login_active %}

{% block title %}{% trans "Log in" %}{{ block.super }}{% endblock title %}

{% block headcss %}
    <style>
        #info_block {
            margin-top: 30px;
        }
    </style>
{% endblock headcss %}

{% block content %}
    <div class="container">
        <form method="post" class="basic-form">
            {% csrf_token %}
            <h3 class="no-margin-top">{% trans "Log in" %}</h3>

            {{ form.as_p }}

            <input type="submit" value="{% trans 'Log in' %}" class="submit btn btn-success btn-md" />
        </form>
        <div id="info_block">
            {% if not restricted %}
                {% blocktrans %}If you don't have a login, please <a href="{{ sign_up_url }}">sign up</a>.{% endblocktrans %}
            {% else %}
                {% blocktrans %}If you don't have a login, please contact your administrator.{% endblocktrans %}
            {% endif %}
        </div>
    </div>
{% endblock content %}